# -*- coding: utf-8 -*-
"""Data_Cleaning_Preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16CbGBTDUVBZ5DyazevBNYkLT6p8ouQQH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""***1. Data Cleaning and Preprocessing***"""

#Load the dataset
df = pd.read_csv('/content/bank-full.csv',sep=";")

df.head(5)

df.info()

df.shape

#Identify missing values
df.isnull().sum()

#IF Missing contain in dataset Handle Missing Values
#num_cols = df.select_dtypes(include=["int64",float64]).columns
#cat_cols = df.select_dtypes(include=["object"]).columns

#Numeric Missing values
#df[num_cols] = df[num_cols].fillna(df[num_cols].median())

#Categorical missing values
#for col in cat_cols:
#  df[col] = df[col].fillna(df[col].mode()[0])

#Check duplicates
df.duplicated().sum()

#If duplicates exist:
#df = df.drop_duplicates()

#Standardize Categorical Columns
cat_cols = df.select_dtypes(include=["object"]).columns

for col in cat_cols:
  df[col] = df[col].str.strip().str.lower()

#Check Standardize columns
for col in cat_cols:
  print(col, df[col].unique()[:10])

#Encode Target Variable (y)
df["y"] = df["y"].map({
    "no":0,
    "yes":1
})
print(df["y"].value_counts())

#Check Result:
print("Missing values: ")
print(df.isnull().sum())

print("\nTarget distribution: ")
print(df["y"].value_counts())

print("\nFinal dataset: ")
print(df.head())

df.to_csv(
    '/content/bank_cleaned.csv',
    index=False
)

