# -*- coding: utf-8 -*-
"""Exploratory_Data_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16CbGBTDUVBZ5DyazevBNYkLT6p8ouQQH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""***2.Exploratory Data Analysis***"""

#Load the dataset
df = pd.read_csv('/content/bank_cleaned.csv')

#Age Distribution

plt.figure(figsize=(10,5))
sns.histplot(df["age"],bins=30,kde=True)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Number of Clients")
plt.show()

#Age by Job

plt.figure(figsize=(12,6))
sns.boxplot(x="job",y="age",data=df)
plt.xticks(rotation=45)
plt.title("Age Distribution by Job")
plt.show()

#Job Analysis
sns.countplot(y="job",data=df, order = df['job'].value_counts().index)
plt.title("Clients by Job")
plt.show()

#Marital Status Analysis
df['marital'].value_counts()

sns.countplot(
    data=df,
    x='marital'
)

plt.title("Clients by Marital Status")
plt.show()

#Education Analysis
df['education'].value_counts()

sns.countplot(
    data=df,
    x='education'
)

plt.title("Education Distribution")
plt.show()

#Term Deposit Subscription by Education
pd.crosstab(
    df['education'],
    df['y'],
    normalize='index'
)*100

#Loan Analysis
loan_analysis = pd.crosstab(
    df['housing'],
    df['loan']
)

#Visualization
sns.countplot(
    data=df,
    x='housing',
    hue='loan'
)

plt.title("Housing Loan vs Personal Loan")
plt.show()

#Loan percentage
pd.crosstab(
    df['housing'],
    df['loan'],
    normalize='index'
)*100

#campaign Analysis
df['campaign'].describe()

#Visualization:

plt.figure(figsize=(10,5))
sns.histplot(data=df,
             x="campaign",
             bins=30
             )
plt.title("Campaign Distribution")
plt.xlabel("Number of Contacts")
plt.show()

#Campaign Success Rate

campaign_success = (
    df.groupby('campaign')['y']
    .mean()
    .reset_index()
)

#Convert to Percentage:
campaign_success = campaign_success.rename(columns={'y':'success_rate'})
campaign_success['success_rate'] = campaign_success['success_rate']*100

plt.figure(figsize=(10,5))
sns.lineplot(
    data=campaign_success,
    x='campaign',
    y='success_rate'
)

plt.title("Campaign Contact vs Subscription Success Rate")
plt.ylabel("Success Rate (%)")
plt.show()

