# -*- coding: utf-8 -*-
"""Statistical Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16CbGBTDUVBZ5DyazevBNYkLT6p8ouQQH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""***3.Statistical Analysis***"""

#Load the dataset
df = pd.read_csv('/content/bank_cleaned.csv')

#Hypothesis Testing
#Creates two groups
housing_yes = df[df['housing'] == 'yes']['balance']
housing_no = df[df['housing'] == 'no']['balance']

#Calculate means
print(housing_yes.mean())
print(housing_no.mean())

#Independent Two-Sample T-Test
from scipy.stats import ttest_ind

t_stat, p_value = ttest_ind(
    housing_yes,
    housing_no,
    equal_var=False
)
print("T-statistic: ", t_stat)
print("P-value: ", p_value)

#Decision

alpha = 0.05

if p_value < alpha:
  print("Reject H0")
else:
  print("Fail to reject H0")

#Correlation Analysis:
corr_cols = [
    'duration',
    'campaign',
    'previous',
    'pdays',
    'y'
]

corr_matrix = df[corr_cols].corr()
corr_matrix

#Heatmap:
plt.figure(figsize=(8,6))

sns.heatmap(
    corr_matrix,
    annot=True,
    cmap='coolwarm'
)

plt.title('Campaign Variables Correlation')
plt.show()