# -*- coding: utf-8 -*-
"""model_trainingAnalysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16CbGBTDUVBZ5DyazevBNYkLT6p8ouQQH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""***4.Machine Learning***"""

#Load the dataset
df = pd.read_csv('/content/bank_cleaned.csv')

#Separate X and Y

x = df.drop('y',axis=1)
y = df['y']

#Identify Categorical Columns
categorical_cols = x.select_dtypes(
    include='object'
).columns

numeric_cols = x.select_dtypes(
    exclude='object'
).columns

#Train-Test Split

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(
    x,y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

#Preprocessing Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,OneHotEncoder

#Preprocessing:
preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            numeric_cols
        ),
        (
            'cat',
            OneHotEncoder(
                handle_unknown='ignore'
            ),
            categorical_cols
        )
    ]
)

#Logistic Regression Model
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

model = Pipeline(
    steps = [
        ('preprocessor',preprocessor),
        ('classifier',LogisticRegression(
            max_iter=1000
        ))
    ]
)

model1 = Pipeline(
    steps = [
        ('preprocessor',preprocessor),
        ('classifier',DecisionTreeClassifier(
            random_state=42
        ))
    ]
)

model2 = Pipeline(
    steps = [
        ('preprocessor',preprocessor),
        ('classifier',RandomForestClassifier(
            n_estimators=200,
            random_state=42
        ))
    ]
)

#Train Logistic Regression:
model.fit(x_train, y_train)

#Train Decision Tree
model1.fit(x_train, y_train)

#Train Random Forest:
model2.fit(x_train, y_train)

#Predict Logistic Reggression:
y_pred = model.predict(x_test)

#Predict Decision Tree
y_pred1 = model1.predict(x_test)

#Predict Random Forest
y_pred2 = model2.predict(x_test)

#Model Evaluation
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

#Calculate

accuracy = accuracy_score(y_test,y_pred)*100

precision = precision_score(y_test,y_pred)*100

recall = recall_score(y_test,y_pred)*100

f1 = f1_score(y_test,y_pred)*100

print(f'Accuracy : {accuracy}')
print(f'Precision : {precision}')
print(f'Recall: {recall}')
print(f'F1 Score: {f1}')
print(classification_report(y_test, y_pred))

#Calculate

accuracy1 = accuracy_score(y_test,y_pred1)*100

precision1 = precision_score(y_test,y_pred1)*100

recall1 = recall_score(y_test,y_pred1)*100

f11 = f1_score(y_test,y_pred1)*100

print(f'Accuracy : {accuracy1}')
print(f'Precision : {precision1}')
print(f'Recall: {recall1}')
print(f'F1 Score: {f11}')
print(classification_report(y_test, y_pred1))

#Calculate

accuracy2 = accuracy_score(y_test,y_pred2)*100

precision2 = precision_score(y_test,y_pred2)*100

recall2 = recall_score(y_test,y_pred2)*100

f12 = f1_score(y_test,y_pred2)*100

print(f'Accuracy : {accuracy2}')
print(f'Precision : {precision2}')
print(f'Recall: {recall2}')
print(f'F1 Score: {f12}')
print(classification_report(y_test, y_pred2))

cm = confusion_matrix(
    y_test,
    y_pred
)

sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

cm1 = confusion_matrix(
    y_test,
    y_pred1
)

sns.heatmap(
    cm1,
    annot=True,
    fmt='d'
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

cm2 = confusion_matrix(
    y_test,
    y_pred2
)

sns.heatmap(
    cm2,
    annot=True,
    fmt='d'
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

print("Model                   Accuracy   Precision    Recall    F1 ")
print("________________________________________________________________________")
print(f"Logistic Regression :    {accuracy:.2f}       {precision:.2f}       {recall:.2f}   {f1:.2f}")
print("________________________________________________________________________")
print(f"Decision Tree :          {accuracy1:.2f}       {precision1:.2f}       {recall1:.2f}   {f11:.2f}")
print("________________________________________________________________________")
print(f"Random Forest :          {accuracy2:.2f}       {precision2:.2f}       {recall2:.2f}   {f12:.2f}")

